project: remix-test

apps:
  front:
    build: manual
    domain: remix.172.245.84.56.sslip.io
    port: 3000
    envs:
      PB_URL: ${this.pocketbase.internal}

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    volumes:
      pb-volume: /pb_data
    domain: pb.172.245.84.56.sslip.io
    port: 8090
