project: lev-docs

apps:
  main:
    build: manual
    dockerfile: Dockerfile.docs
    proxy:
      - domain: leverans.dev
        port: 8000

services:
  dozzle:
    image: amir20/dozzle:latest
    domain: dozzle.leverans.dev
    port: 8080
    mounts:
      "/var/run/docker.sock": "/var/run/docker.sock"

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    domain: umami.leverans.dev
    port: 3000
    envs:
      DATABASE_URL: postgresql://umami:umami@lev-docs-umami-db-service:5432/umami
      DATABASE_TYPE: postgresql

  umami-db:
    image: postgres:15-alpine
    envs:
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
      POSTGRES_DB: umami
    volumes:
      umami-db-data: /var/lib/postgresql/data
