# Включаем интерфейс админ-панели на 8080 порту
[api]
  dashboard = true
  insecure = true

# Логирование (опционально)
[log]
  level = "INFO"

# Настройка доступа к Docker API для автоматического обнаружения сервисов
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false  # Отключает автопубликацию для всех контейнеров по умолчанию
  swarmMode = true

# Включаем HTTP и HTTPS с поддержкой Let's Encrypt
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com" # Укажите свою почту
  storage = "acme.json"             # Файл для хранения сертификатов
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"               # Использование HTTP-решения для проверки доменов

