[package]
name = "docs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
anyhow = "1.0.93"
askama = "0.12.1"
pulldown-cmark = "0.12.2"
serde = {version = "1.0.215",  features = ["derive"]}
serde_yaml = "0.9.34"
walkdir = "2.5.0"
